### ISSUE TITLE
Start Test Case

### ISSUE THREAD

**Issue by byoriam** [TheoGa/TU_SEP_Test_Cases#1]
In der reference zum start test case steht:

[ERR] Wrong usage: ./basic <price_lemonade> <price_lemon> <price_sugar>

sollte dies nicht eher

[ERR] Wrong usage: ./test_program/basic <price_lemonade> <price_lemon> <price_sugar>

sein, da das Programm ja mit "./test_program/basic" gestartet wird...

**Comment by TheoGa** [comment]
Ja deine Logik stimmt und es sollte normalerweise auch so sein, nur in unserem Fall für das Uni Beispiel soll die Fehlermeldung genau so aussehen wie es im reference file steht, da sonst die Test Cases der Uni nicht funktionieren würden.
