### ISSUE TITLE
General testcase

### ISSUE THREAD

**Issue by julthon** [TheoGa/TU_SEP_Test_Cases#2]
diese anmerkung wird nicht beachtet bei deinem general testcase:
> Achtung: Falls kein Befehl eingegeben wurde (nur '\n'), wird ohne Fehlermeldung das Standard-Prompt erneut ausgegeben.

**Comment by TheoGa** [comment]
Diese Anmerkung wird beachtet - siehe general_CORRECT.txt erste Zeile - "sep> sep> [ERR] Unknown command." 

das erste "sep>" steht hierbei für den erneut ausgegebenen Prompt
